name: CI

on:
  workflow_dispatch:
  push:
  pull_request:


defaults:
  run:
    shell: bash -l {0}


jobs:

  build_page:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        emsdk_ver: ["3.1.2"]

    steps:
      - uses: actions/checkout@v2


      - name: Install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: env.yaml
          environment-name: pyjs-wasm
          micromamba-version: "0.23.2"

      
      - name: build page
        run: |
          micromamba activate pyjs-wasm

          
          mkdir build
          pushd build

          micromamba create -n pyjs-browser-env \
            --platform=emscripten-32 \
            -c https://repo.mamba.pm/emscripten-forge \
            -c https://repo.mamba.pm/conda-forge \
            --yes \
            "pyjs==0.8.0" numpy


          # donload empack config
          EMPACK_CONFIG=empack_config.yaml
          echo "donwload empack config"
          wget -O $EMPACK_CONFIG https://raw.githubusercontent.com/emscripten-forge/recipes/main/empack_config.yaml


          # pack the environment in a js/data file
          empack pack env --env-prefix $MAMBA_ROOT_PREFIX/envs/pyjs-browser-env --outname python_data --config empack_config.yaml


          # copy relevant files from build to page
          cp python_data.js   ../page  
          cp python_data.data ../page


          # copy relevant files from env to page
          cp $MAMBA_ROOT_PREFIX/envs/pyjs-browser-env/lib_js/pyjs/pyjs_runtime_browser* ../page

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./page
          enable_jekyll: false