name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: build-environment.yaml
          environment-name: pyjs-build-env
          micromamba-version: "1.4.2"

      - name: Build the page
        run: |
          # TODO: run build script

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
